Repository Chris-Johnston/CSS452Game, pull requests merged in 2018-03, with the labels that each got.

#30 Add engine logger util that was removed by demo branch merge
  public_html/src/Engine/Core/Engine_Logger.js
Labels: bug, enhancement

#32 Add world bounds
  public_html/index.html
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/WorldBounds.js
Labels: Ready for merge, enhancement

#35 Added health bar
  public_html/index.html
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/HealthBar.js
  public_html/src/MyGame/Objects/Hobbes.js
Labels: enhancement

#37 Refactor health bar to be more robust and support horizontal orientation
  public_html/index.html
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/HealthBar.js
Labels: enhancement

#39 Adjusted the jumping physics for Hobbes so that he will jump ~25 high…
  public_html/src/MyGame/Objects/Hobbes.js
Labels: enhancement

#36 Implemented water balloon object. Water balloon is currently thrown a…
  public_html/assets/Balloon.png
  public_html/src/Engine/GameObjects/GameObjectSet.js
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/Hobbes.js
  public_html/src/MyGame/Objects/MinionEmitter.js
  public_html/src/MyGame/Objects/SphereMinion.js
  public_html/src/MyGame/Objects/SquirtGunShot.js
  public_html/src/MyGame/Objects/WaterBalloon.js
Labels: enhancement

#44 Add boss
  public_html/assets/spacebot-violet.png
  public_html/index.html
  public_html/src/Engine/GameObjects/GameObjectSet.js
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/Boss.js
  public_html/src/MyGame/Objects/FloaterBoss.js
Labels: enhancement

#52 Add playtest demo bells and whistles (make the index page look nicer)
  public_html/assets/web_background.jpg
  public_html/assets/web_background.xcf
  public_html/css/style.css
  public_html/index.html
Labels: enhancement

#59 Rebind Keys and support rapid fire
  public_html/index.html
  public_html/src/MyGame/Objects/Hobbes.js
Labels: enhancement

#63 Added music and sound effects
  public_html/assets/sounds/hurt.ogg
  public_html/assets/sounds/kelvin_373_main_theme.ogg
  public_html/assets/sounds/kelvin_373_title.ogg
  public_html/assets/sounds/zap.ogg
  public_html/src/MyGame/GameOver.js
  public_html/src/MyGame/MainMenu.js
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/Hobbes.js
  public_html/src/MyGame/WinScreen.js
Labels: enhancement

#60 Add Another Level
  public_html/assets/background_purple.png
  public_html/assets/background_purple.xcf
  public_html/assets/background_purple_normal.png
  public_html/assets/background_purple_normal.xcf
  public_html/assets/bluegridplat_512x128.png
  public_html/assets/bluegridplat_512x128.xcf
  public_html/assets/squareboss_sprites.png
  public_html/assets/squareboss_sprites.xcf
  public_html/index.html
  public_html/src/Engine/RigidShapes/RigidShape.js
  public_html/src/MyGame/AnotherLevel.js
  public_html/src/MyGame/Level2.js
  public_html/src/MyGame/MyGame.js
  public_html/src/MyGame/Objects/LightPlatform.js
  public_html/src/MyGame/Objects/SquareBoss.js
Labels: Work In Progress
